# vim: set filetype=python:'

# This file is part of File Collection Manager
# Copyright (C) 2009 Brian Allen Vanderburg II
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.


# Requirements
Import('*')
lenv = defenv.Clone()


# Sources
sources = ['aboutdlg.cpp',
           'actions.cpp',
           'app.cpp',
           'art.cpp',
           'checksum.cpp',
           'dnd.cpp',
           'editpanel.cpp',
           'log.cpp',
           'mainwnd.cpp',
           'options.cpp',
           'collection/collection.cpp',
           'collection/depends.cpp',
           'collection/dir.cpp',
           'collection/file.cpp',
           'collection/node.cpp',
           'collection/package.cpp',
           'collection/version.cpp']

# config.h
lenv.SubstFile('config.h', 'config.h.in')
lenv.Append(CPPPATH='${TARGET.dir}')

# Build
lenv.Merge([deflibs['wx'], deflibs['mhash']])

program = lenv.Program('fcman', sources)

Default(program)
Alias('program', program)

# Packages
defenv.InstallPackageAccum('bin', '.', program, scan=0)

